### ISSUE TITLE
Port to dotnet core (.NET Core) 1.0.0 RTM

### ISSUE THREAD

**Issue by konard** [Konard/ASP.NET-5-CoreCLR-WebSocket-Example#4]
https://github.com/aspnet/cli-samples

**Comment by konard** [comment]
This should be done as fork to "ASP.NET-Core-WebSocket-Example". (https://github.com/aspnet/Announcements/issues/176)

**Comment by konard** [comment]
https://docs.asp.net/en/latest/getting-started.html

**Comment by atonamy** [comment]
So how to make it run this example? I can't make it work

**Comment by atonamy** [comment]
@Konard
I have this issue 

Reference to type 'WebSocket' claims it is defined in 'System', but it could not be found. 

When I try to run this project in new 1.0 .Net Core
